apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-6wfh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tmnu-tenant/rhtap-demo-app/hacbs-test-project-6wfh@sha256:3637c48bba78670d2b2c8a75b10c7393cc8885f8224e5fa92906692b34c97945
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
